route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'ses'
receivers:
  - name: 'ses'
    email_configs:
      - smarthost: email-smtp.us-east-1.amazonaws.com:587
        auth_username: AKIAUY4V3WXPU3RPEAXV
        auth_password: BNYw8NT3NI1p4mS9JbI53FrSukU7OLe9xFY+oEUEasHP
        from: surya.manimohan@gmail.com
        to: manimohan.t22@gmail.com
        headers:
          subject: Prometheus Alert Mail
inhibit_rules:
  - source_match: 
      severity: 'critical'
    target_match: 
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
