route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'ses'
receivers:
  - name: 'ses'
    email_configs:
      - smarthost: ray7kyxr8yry.fips.wmjb.mail-manager-smtp.amazonaws.com:587
        auth_username: inp-i7cudrx4zxybnrnsjvseglha
        auth_password: 4RRdNJPsd0Yif(i1LK*U?7xN[+of$nw7
        from: surya.manimohan@gmail.com
        to: manimohan.t22@gmail.com
        headers:
          subject: Prometheus Alert Mail
inhibit_rules:
  - source_match: 
      severity: 'critical'
    target_match: 
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
